spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root1234
    url: jdbc:mysql://192.168.3.126:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: admin
    password: admin
    host: 1.15.114.101
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 1.15.114.101
    database: 0
    port: 6379
    password: root
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/